<a href="https://colab.research.google.com/github/Casheww10/AI/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [2]:
# import numpy module with alias np
import numpy as np



We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [3]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
import numpy as np

arr = np.array([1, 2, 3])



In [4]:
# print output
print(arr)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [5]:
#define a,b,c and d as instructed above

# a =
# b =
# c =
# d =
import numpy as np

# Define numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

# Print the arrays
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)



a: [1 2 3]
b: [4 5 6]
c: [7 8 9]
d: [10 11 12]


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [6]:
#print dimentions of a,b, c and d

import numpy as np

# Define numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

# Print dimensions
print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)
print("Dimension of c:", c.ndim)
print("Dimension of d:", d.ndim)




Dimension of a: 1
Dimension of b: 1
Dimension of c: 1
Dimension of d: 1


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [7]:
# print shape of each a,b ,c and d
import numpy as np

# Define numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

# Print shapes
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)






Shape of a: (3,)
Shape of b: (3,)
Shape of c: (3,)
Shape of d: (3,)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [8]:
# print data type of c and d
import numpy as np

# Define numpy arrays
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

# Print data types
print("Data type of c:", c.dtype)
print("Data type of d:", d.dtype)





Data type of c: int64
Data type of d: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [9]:
# print data type of c and d
import numpy as np

# Define numpy arrays
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

# Print data types
print("Data type of c:", c.dtype)
print("Data type of d:", d.dtype)







Data type of c: int64
Data type of d: int64


In [10]:
# Lets check length of array b, using len() function
# len(b)
import numpy as np

# Define numpy array
b = np.array([4, 5, 6])

# Check length
print("Length of b:", len(b))


Length of b: 3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [11]:
# Define l1,l2,l3 and l4 as stated above.
# l1 =
# l2 =
# l3 =
# l4 =
import numpy as np

# Define numpy arrays
l1 = np.array([1, 2, 3, 4])
l2 = np.array([5, 6, 7, 8])
l3 = np.array([9, 10, 11, 12])
l4 = np.array([13, 14, 15, 16])

# Print arrays
print("l1:", l1)
print("l2:", l2)
print("l3:", l3)
print("l4:", l4)



l1: [1 2 3 4]
l2: [5 6 7 8]
l3: [ 9 10 11 12]
l4: [13 14 15 16]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [12]:
#code here as instructed above

import numpy as np

# Define lists
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

# Measure execution time using list comprehension
%timeit [l1[i] * l2[i] for i in range(len(l1))]



472 ns ± 6.49 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [13]:
import numpy as np

# Define lists
l3 = [9, 10, 11, 12]
l4 = [13, 14, 15, 16]

# Measure execution time using list comprehension
%timeit [l3[i] * l4[i] for i in range(len(l3))]




472 ns ± 7.23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [14]:
#Create a numpy array using arange with 1 and 11 as parameter in it


import numpy as np

# Create numpy array using arange
arr = np.arange(1, 11)

# Print the array
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [15]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
import numpy as np

# Create numpy array using arange with step size 2
arr = np.arange(1, 11, 2)

# Print the array
print(arr)




[1 3 5 7 9]


In [16]:
# create numpy array using eye function with 3 as passed parameter
import numpy as np

# Create a 3x3 identity matrix
arr = np.eye(3)

# Print the array
print(arr)





[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=

import numpy as np

# Create numpy array x with numbers from 1 to 16
x = np.arange(1, 17)

# Print the array
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [18]:
import numpy as np

# Create numpy array x
x = np.arange(1, 17)

# Reshape x into 2 rows and 8 columns
x_reshaped = x.reshape(2, 8)

# Print the reshaped array
print(x_reshaped)



[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [19]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
import numpy as np

# Create numpy array x
x = np.arange(1, 17)

# Reshape x into (2, 4, 2)
x_reshaped = x.reshape(2, 4, 2)

# Print the reshaped array
print(x_reshaped)




[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [20]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

import numpy as np

# Create numpy array x
x = np.arange(1, 17)

# Reshape x into a 4×4 matrix using an unknown dimension
x_reshaped = x.reshape(4, -1)

# Print the reshaped array
print(x_reshaped)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# y=


# print y
import numpy as np

# Create numpy array x
x = np.arange(1, 17)

# Reshape x into a 3D array with 2 arrays containing 4 arrays each
y = x.reshape(2, 4, -1)

# Print the reshaped array
print(y)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [22]:
# Flattening y
import numpy as np

# Create numpy array x
x = np.arange(1, 17)

# Reshape x into a 3D array
y = x.reshape(2, 4, -1)

# Flatten y
y_flattened = y.flatten()

# Print the flattened array
print(y_flattened)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [23]:
# Get third element in array a
import numpy as np

# Define numpy array a
a = np.array([1, 2, 3, 4, 5])

# Get the third element (index 2)
third_element = a[2]

# Print the third element
print("Third element of a:", third_element)


Third element of a: 3


In [24]:
#Print 3rd, 5th, and 7th element in array a

import numpy as np

# Define numpy array a
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Get the 3rd, 5th, and 7th elements (indices 2, 4, and 6)
selected_elements = a[[2, 4, 6]]

# Print the selected elements
print("3rd, 5th, and 7th elements:", selected_elements)



3rd, 5th, and 7th elements: [3 5 7]


Lets check the same for 2 D array

In [25]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
# a =
import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Print the array
print(a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# print the 3rd element from the 3rd row of a
import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Get the 3rd element from the 3rd row (row index 2, column index 2)
third_element = a[2, 2]

# Print the result
print("3rd element from the 3rd row:", third_element)



3rd element from the 3rd row: 9


Well done!

Now lets check indexing for 3 D array

In [27]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# b =
import numpy as np

# Define 3D numpy array b
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

# Print the array
print(b)




[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Extracting the 3rd element from the 2nd list (which is the 1st list in the nested structure)
element = a[1, 2]

# Print the result
print("3rd element from the 2nd list (1st list in nested structure):", element)



3rd element from the 2nd list (1st list in nested structure): 6


In [29]:
# Create 1D array

# arr=


import numpy as np

# Create a 1D numpy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print(arr)


[1 2 3 4 5]


In [30]:
# Slice elements from 1st to 5th element from the following array:

import numpy as np

# Define a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from 1st to 5th (index 0 to 4)
sliced_arr = arr[0:5]

# Print the sliced array
print("Sliced elements (1st to 5th):", sliced_arr)




Sliced elements (1st to 5th): [10 20 30 40 50]


Note: The result includes the start index, but excludes the end index.



In [31]:
# Slice elements from index 5 to the end of the array:
import numpy as np

# Define a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from index 5 to the end
sliced_arr = arr[5:]

# Print the sliced array
print("Sliced elements (index 5 to end):", sliced_arr)





Sliced elements (index 5 to end): [60 70 80 90]


In [32]:
# Slice elements from the beginning to index 5 (not included):
import numpy as np

# Define a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from the beginning to index 5 (not included)
sliced_arr = arr[:5]

# Print the sliced array
print("Sliced elements (beginning to index 5, not included):", sliced_arr)





Sliced elements (beginning to index 5, not included): [10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [33]:
# Print every other element from index 1 to index 7:

import numpy as np

# Define a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice every other element from index 1 to index 7
sliced_arr = arr[1:8:2]

# Print the sliced array
print("Every other element from index 1 to 7:", sliced_arr)



Every other element from index 1 to 7: [20 40 60 80]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [34]:
# Return every other element from the entire array arr:
import numpy as np

# Define a sample 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice every other element from the entire array
sliced_arr = arr[::2]

# Print the result
print("Every other element from the entire array:", sliced_arr)




Every other element from the entire array: [10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [35]:
# Print array a
print(a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18]])

# Slice from the third row (index 2), elements from index 1 to 5 (not included)
sliced_elements = a[2, 1:5]

# Print the result
print("Sliced elements:", sliced_elements)



Sliced elements: [14 15 16 17]


In [37]:
# In array 'a' print index 2 from all the elements :
import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18]])

# Extract index 2 (third column) from all rows
column_at_index_2 = a[:, 2]

# Print the result
print("Index 2 from all elements:", column_at_index_2)





Index 2 from all elements: [ 3  9 15]


In [38]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
import numpy as np

# Define 2D numpy array a
a = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18]])

# Slice from index 1 till the end (for all rows)
sliced_array = a[:, 1:]

# Print the result
print("Sliced array from index 1 till end:\n", sliced_array)





Sliced array from index 1 till end:
 [[ 2  3  4  5  6]
 [ 8  9 10 11 12]
 [14 15 16 17 18]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [39]:
# x1=
import numpy as np

# Create an array
x1 = np.array([10, 20, 30, 40])

# Create a copy
copy_x1 = x1.copy()

# Create a view
view_x1 = x1.view()

# Modify the copied array
copy_x1[0] = 99  # This won't affect the original array

# Modify the viewed array
view_x1[1] = 88  # This will affect the original array

# Print all arrays
print("Original x1:", x1)          # [10 88 30 40] (changed due to view)
print("Copy of x1:", copy_x1)      # [99 20 30 40] (unchanged original)
print("View of x1:", view_x1)      # [10 88 30 40] (same as original)



Original x1: [10 88 30 40]
Copy of x1: [99 20 30 40]
View of x1: [10 88 30 40]


In [40]:
# assign x2 = x1
import numpy as np

# Create an array
x1 = np.array([10, 20, 30, 40])

# Assign x2 to x1 (this does NOT create a new array, just a reference)
x2 = x1

# Modify x2
x2[0] = 99

# Print arrays
print("x1 after modifying x2:", x1)  # [99 20 30 40] (changed!)
print("x2:", x2)                     # [99 20 30 40] (same as x1)



x1 after modifying x2: [99 20 30 40]
x2: [99 20 30 40]


In [41]:
#print x1 and x2

import numpy as np

# Create an array
x1 = np.array([10, 20, 30, 40])

# Assign x2 to x1 (they share the same memory)
x2 = x1

# Print both arrays
print("x1:", x1)
print("x2:", x2)



x1: [10 20 30 40]
x2: [10 20 30 40]


Ok now you have seen that both of them are same

In [42]:
# change 1st element of x2 as 10

import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Assign x2 to x1 (both share the same memory)
x2 = x1

# Change the 1st element of x2 to 10
x2[0] = 10

# Print both arrays
print("x1:", x1)  # [10 20 30 40] (changed!)
print("x2:", x2)  # [10 20 30 40] (same as x1)



x1: [10 20 30 40]
x2: [10 20 30 40]


In [43]:
#Again print x1 and x2
import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Assign x2 to x1 (they share the same memory)
x2 = x1

# Modify the 1st element of x2
x2[0] = 10

# Print both arrays again
print("x1:", x1)  # [10 20 30 40] (changed!)
print("x2:", x2)  # [10 20 30 40] (same as x1)






x1: [10 20 30 40]
x2: [10 20 30 40]


In [44]:
# Check memory share between x1 and x2
import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Assign x2 to x1 (both reference the same memory)
x2 = x1

# Check if x1 and x2 share memory
print("Do x1 and x2 share memory?", np.may_share_memory(x1, x2))  # True
print("Do x1 and x2 share memory?", np.shares_memory(x1, x2))  # True



Do x1 and x2 share memory? True
Do x1 and x2 share memory? True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [45]:
# Create a view of x1 and store it in x3.
# x3 =
import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Create a view of x1
x3 = x1.view()

# Print both arrays
print("x1:", x1)
print("x3 (view of x1):", x3)



x1: [99 20 30 40]
x3 (view of x1): [99 20 30 40]


In [46]:
# Again check memory share between x1 and x3

import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Create a view of x1
x3 = x1.view()

# Check if x1 and x3 share memory
print("Do x1 and x3 share memory?", np.shares_memory(x1, x3))  # True



Do x1 and x3 share memory? True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [47]:
#Change 1st element of x3=100

import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Create a view of x1
x3 = x1.view()

# Modify the first element of x3
x3[0] = 100

# Print both arrays
print("x1 after modifying x3:", x1)  # [100 20 30 40] (changed!)
print("x3:", x3)  # [100 20 30 40] (same as x1)


x1 after modifying x3: [100  20  30  40]
x3: [100  20  30  40]


In [48]:
#print x1 and x3 to check if changes reflected in both

import numpy as np

# Create an array
x1 = np.array([99, 20, 30, 40])

# Create a view of x1
x3 = x1.view()

# Modify the first element of x3
x3[0] = 100

# Print both arrays
print("x1 after modifying x3:", x1)  # [100 20 30 40] (changed!)
print("x3:", x3)  # [100 20 30 40] (same as x1)



x1 after modifying x3: [100  20  30  40]
x3: [100  20  30  40]


Now its proved.

Lets see how **Copy()** function works

In [49]:
# Now create an array x4 which is copy of x1

# x4=

import numpy as np

# Create an array
x1 = np.array([100, 20, 30, 40])

# Create an independent copy of x1
x4 = x1.copy()

# Print both arrays
print("x1:", x1)
print("x4 (copy of x1):", x4)


x1: [100  20  30  40]
x4 (copy of x1): [100  20  30  40]


In [50]:
# Change the last element of x4 as 900
import numpy as np

# Create an array
x1 = np.array([100, 20, 30, 40])

# Create an independent copy of x1
x4 = x1.copy()

# Modify the last element of x4
x4[-1] = 900

# Print both arrays
print("x1:", x1)  # [100 20 30 40] (unchanged)
print("x4 after modification:", x4)  # [100 20 30 900] (changed)





x1: [100  20  30  40]
x4 after modification: [100  20  30 900]


In [51]:
# print both x1 and x4 to check if changes reflected in both

import numpy as np

# Create an array
x1 = np.array([100, 20, 30, 40])

# Create an independent copy of x1
x4 = x1.copy()

# Modify the last element of x4
x4[-1] = 900

# Print both arrays
print("x1 (original):", x1)
print("x4 (after modification):", x4)




x1 (original): [100  20  30  40]
x4 (after modification): [100  20  30 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [52]:
#Check memory share between x1 and x4


import numpy as np

# Create an array
x1 = np.array([100, 20, 30, 40])

# Create an independent copy of x1
x4 = x1.copy()

# Check if x1 and x4 share memory
print("Do x1 and x4 share memory?", np.shares_memory(x1, x4))  # Expected output: False


Do x1 and x4 share memory? False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [53]:
# stack x1 and x4 along columns.

import numpy as np

# Create arrays
x1 = np.array([100, 20, 30, 40])
x4 = np.array([100, 20, 30, 900])  # Copy of x1 with modification

# Stack along columns
result = np.column_stack((x1, x4))

# Print the result
print("Stacked array along columns:\n", result)


Stacked array along columns:
 [[100 100]
 [ 20  20]
 [ 30  30]
 [ 40 900]]


In [54]:
#stack x1 and x4 along rows

import numpy as np

# Create arrays
x1 = np.array([100, 20, 30, 40])
x4 = np.array([100, 20, 30, 900])  # Copy of x1 with modification

# Stack along rows
result = np.row_stack((x1, x4))

# Print the result
print("Stacked array along rows:\n", result)


Stacked array along rows:
 [[100  20  30  40]
 [100  20  30 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [55]:
# arr1 =


# arr2 =


##join arr1 and arr2 along rows using concatenate() function

import numpy as np

# Define two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along rows (axis=0)
result = np.concatenate((arr1, arr2), axis=0)

# Print the result
print("Joined array along rows:\n", result)



Joined array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
##join arr1 and arr2 along columns using concatenate() function

import numpy as np

# Define two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along columns (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

# Print the result
print("Joined array along columns:\n", result)



Joined array along columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [57]:
# append arr2 to arr1
import numpy as np

# Define two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Append arr2 to arr1 along rows
result = np.append(arr1, arr2, axis=0)

# Print the result
print("Appended array along rows:\n", result)




Appended array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Lets use insert() function which Inserts values into array before specified index value

In [58]:
# Inserts values into array x1 before index 4 with elements of x4

import numpy as np

# Define arrays
x1 = np.array([100, 20, 30, 40])
x4 = np.array([100, 20, 30, 900])

# Insert x4 into x1 before index 4
result = np.insert(x1, 4, x4)

# Print the result
print("Array after insertion:\n", result)



Array after insertion:
 [100  20  30  40 100  20  30 900]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [59]:
# delete 2nd element from array x2
import numpy as np

# Define array
x2 = np.array([100, 20, 30, 40])

# Delete the 2nd element (index 1)
result = np.delete(x2, 1)

# Print the result
print("Array after deletion:", result)





Array after deletion: [100  30  40]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!